/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Farmacia.Interfaz;

import Farmacia.Empleado;
import Farmacia.Farmacia;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;

/**
 *
 * @author Diego Sullon
 */
public class RegistrarEmpleados extends javax.swing.JFrame {
    private Empleado empleado;
    private Farmacia farmacia;
    /**
     * Creates new form RegistrarEmpleado
     */
    
    public RegistrarEmpleados(Empleado empleado, Farmacia farmacia) {
        this.empleado = empleado;
        this.farmacia = farmacia;
        initComponents();
        buttonGroupGenero.add(masculino);
        buttonGroupGenero.add(femenino);
        this.empleado=empleado; 
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    public RegistrarEmpleados() {
        initComponents();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGenero = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        inDni = new javax.swing.JTextField();
        inNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        inTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        masculino = new javax.swing.JRadioButton();
        femenino = new javax.swing.JRadioButton();
        inSueldo = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        inCorreo = new javax.swing.JTextField();
        registrarButton = new javax.swing.JButton();
        inCargo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        inDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inDniActionPerformed(evt);
            }
        });
        jPanel2.add(inDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 157, 22));

        inNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inNombreActionPerformed(evt);
            }
        });
        jPanel2.add(inNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 157, 22));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Cargo:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("DNI:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setText("Nuevo empleado");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        inTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inTelefonoActionPerformed(evt);
            }
        });
        jPanel2.add(inTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 157, 22));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Telefono:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Sueldo:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Genero:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        masculino.setBackground(new java.awt.Color(255, 255, 255));
        masculino.setSelected(true);
        masculino.setText("Masculino");
        masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masculinoActionPerformed(evt);
            }
        });

        femenino.setBackground(new java.awt.Color(255, 255, 255));
        femenino.setText("Femenino");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(masculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(femenino)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masculino)
                    .addComponent(femenino))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 160, -1));

        inSueldo.setModel(new javax.swing.SpinnerNumberModel(930.6f, null, null, 1.0f));
        jPanel2.add(inSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Correo:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        inCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inCorreoActionPerformed(evt);
            }
        });
        inCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inCorreoKeyTyped(evt);
            }
        });
        jPanel2.add(inCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 157, 22));

        registrarButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        registrarButton.setText("Registrar");
        registrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarButtonActionPerformed(evt);
            }
        });
        jPanel2.add(registrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 128, 45));

        inCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cajero", "Asistente", "Gerente" }));
        jPanel2.add(inCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 160, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inDniActionPerformed

    private void inNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inNombreActionPerformed

    private void inTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inTelefonoActionPerformed

    private void registrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarButtonActionPerformed
        // TODO add your handling code here:
        String dni = inDni.getText();
        String cargo = inCargo.getSelectedItem().toString();
        String nombre = inNombre.getText();
        String telefono = inTelefono.getText();
        String correo = inCorreo.getText();
        if(!dni.isEmpty()&&!cargo.isEmpty()&&!nombre.isEmpty()&&!telefono.isEmpty()&&!correo.isEmpty()){
            boolean genero = true;
            if (femenino.isSelected()) {
                genero = false;
            }
            float sueldo = (float) inSueldo.getValue();
            empleado.agregarEmpleado(dni, cargo, nombre, telefono, correo, genero, sueldo, farmacia);
        }
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_registrarButtonActionPerformed

    private void masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masculinoActionPerformed

    }//GEN-LAST:event_masculinoActionPerformed

    private void inCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inCorreoActionPerformed
        // GAAAAAAAAAAAAAAAA:
    }//GEN-LAST:event_inCorreoActionPerformed

    private void inCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inCorreoKeyTyped
        char key = evt.getKeyChar();
        
        if(key==KeyEvent.VK_ENTER){
            registrarButton.doClick();
        }
    }//GEN-LAST:event_inCorreoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGenero;
    private javax.swing.JRadioButton femenino;
    private javax.swing.JComboBox<String> inCargo;
    private javax.swing.JTextField inCorreo;
    private javax.swing.JTextField inDni;
    private javax.swing.JTextField inNombre;
    private javax.swing.JSpinner inSueldo;
    private javax.swing.JTextField inTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JButton registrarButton;
    // End of variables declaration//GEN-END:variables
}
