/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Farmacia.Interfaz;

import Farmacia.Farmacia;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author Diego Sullon
 */
public class RegistrarSedes extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarSedes
     */
    private ArrayList<Farmacia> farmacias;

    public RegistrarSedes(ArrayList<Farmacia> farmacias) {
        this.farmacias = farmacias;
        initComponents();
        this.setAlwaysOnTop(true);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }
    
    public RegistrarSedes() {
        initComponents();
        this.setAlwaysOnTop(true);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inCiudad = new javax.swing.JTextField();
        inSede = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inDirec = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inTelefono = new javax.swing.JTextField();
        inCodigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Telefono:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Código:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Dirección:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        inCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inCiudadActionPerformed(evt);
            }
        });
        jPanel2.add(inCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 149, 157, 22));

        inSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inSedeActionPerformed(evt);
            }
        });
        jPanel2.add(inSede, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 192, 157, 22));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Sede:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        inDirec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inDirecActionPerformed(evt);
            }
        });
        jPanel2.add(inDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 232, 157, 22));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Ciudad: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        inTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inTelefonoActionPerformed(evt);
            }
        });
        jPanel2.add(inTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 157, 22));

        inCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inCodigoActionPerformed(evt);
            }
        });
        jPanel2.add(inCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 157, 22));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 128, 45));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setText("Nueva sede");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inTelefonoActionPerformed

    private void inCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inCodigoActionPerformed

    private void inCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inCiudadActionPerformed

    private void inSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inSedeActionPerformed

    private void inDirecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inDirecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inDirecActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ciudad = inCiudad.getText();
        String sede = inSede.getText();
        String direc = inDirec.getText();
        String telefono = inTelefono.getText();
        String cod = inCodigo.getText();
        if (!inCiudad.getText().isEmpty() && !inSede.getText().isEmpty() && !inDirec.getText().isEmpty() && !inTelefono.getText().isEmpty() && !inCodigo.getText().isEmpty()) {
            Farmacia farmacia3 = new Farmacia(ciudad, sede, direc, telefono, cod);
            farmacias.add(farmacia3);

            System.out.println("asdasdsd");
            this.setVisible(false);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarSedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarSedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarSedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarSedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarSedes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inCiudad;
    private javax.swing.JTextField inCodigo;
    private javax.swing.JTextField inDirec;
    private javax.swing.JTextField inSede;
    private javax.swing.JTextField inTelefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
